# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockettrade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='closed',
            field=models.DateTimeField(null=True),
        ),
    ]
