# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-17 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rockettrade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingitem',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_items', to='rockettrade.Listing'),
        ),
    ]
