# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockettrade', '0002_auto_20160912_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
